
spring:
 #  redis 缓存配置
    cache:
        type: redis       #缓存类型
        cacheName: res   #缓存名称
        redis:
            time-to-live: 300s  #缓存过期时间
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            letters:
            pool:
                max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 8     # 连接池中的最大空闲连接
                min-idle: 0     # 连接池中的最小空闲连接
                max-wait: 5s  # 连接池最大阻塞等待时间（使用负值表示没有限制）
