spring:
  #线程池
  task:
    execution:
      pool:
        core-size: 5            # 核心线程数
        max-size: 10            # 最大线程数
        queue-capacity: 100     # 队列容量
        keep-alive: 60s         # 空闲线程存活时间
      thread-name-prefix: "taskExecutor"